### ISSUE TITLE
labelBackgroundColor crashing

### ISSUE THREAD

**Issue by infaz** [githuboftigran/rn-range-slider#1]
When set labelBackgroundColor, App is getting crashed

**Comment by githuboftigran** [comment]
Colors should have #RRGGBB or #AARRGGBB format. I guess you used #RGB format and app crashed on android :)

**Comment by githuboftigran** [comment]
@infaz I updated this lib, now colors can have the following formats:
#RGB, #RGBA, #RRGGBB, #RRGGBBAA
