### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by devswift2017** [githuboftigran/rn-range-slider#10]
I'm runing on emulator api 27 buid error, iOS run and release normal. I'm dont know this problem is happen.
anyone have solution resolve it. Thanks so much.
<img width="1920" alt="Screen Shot 2019-06-07 at 12 45 03 AM" src="https://user-images.githubusercontent.com/27657751/59054470-f741ec80-88bd-11e9-93fa-fcc7af726766.png">
![Screen Shot 2019-06-07 at 12 49 04 AM (2)](https://user-images.githubusercontent.com/27657751/59054545-1fc9e680-88be-11e9-9c16-0cb686da59e8.png)

**Comment by githuboftigran** [comment]
@devswift2017 , did you try to unlink and link module again?
`react-native unlink rn-range-slider`
`react-native link rn-range-slider`

**Comment by devswift2017** [comment]
Thank you, I just resolve it by update android studio lasted version dont need resolve warning by android studio, now is working.
<img width="1920" alt="Screen Shot 2019-06-07 at 1 10 26 AM" src="https://user-images.githubusercontent.com/27657751/59055900-227a0b00-88c1-11e9-808d-c00b0b83f979.png">

**Comment by githuboftigran** [comment]
Cool, thanks for closing the issue.
