### ISSUE TITLE
Support for Expo

### ISSUE THREAD

**Issue by Badreddinez** [githuboftigran/rn-range-slider#105]
I receive the following on expo 
![image](https://user-images.githubusercontent.com/11504955/122458860-8eaf9f00-cfb0-11eb-9e19-53a762bff0a6.png)

and it would be really great if you support it.
I see this as the best slider existing out there.
Waiting for your feedback!

regards,

**Comment by aminsaedi** [comment]
Hi.

i'm using this lib with expo and there isn't any issue.
You have to import all these props `renderThumb` & `renderRail` & `renderRailSelected` & `renderLabel` & `renderNotch`

You can find basic implementation of needed components (Thumb, Rail, RailSelected, Label, Notch) [here](https://github.com/githuboftigran/rn-widgets-demo/tree/master/src/Slider).

**Comment by Harsh2110mishra** [comment]
> Hi.
> 
> i'm using this lib with expo and there isn't any issue.
> You have to import all these props `renderThumb` & `renderRail` & `renderRailSelected` & `renderLabel` & `renderNotch`
> 
> You can find basic implementation of needed components (Thumb, Rail, RailSelected, Label, Notch) [here](https://github.com/githuboftigran/rn-widgets-demo/tree/master/src/Slider).

Hey Amin, In my App this slider is not showing. Can you please help me to solve this issue?

**Comment by aminsaedi** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23167933/126390254-049ed5a7-ede8-4f95-8fef-71d60ed79103.png">

Here you are :))

I put a zip file below witch has all app.js and other files you need.
please ping me your result
Goodluck.

[Archive.zip](https://github.com/githuboftigran/rn-range-slider/files/6851023/Archive.zip)

**Comment by Harsh2110mishra** [comment]
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/23167933/126390254-049ed5a7-ede8-4f95-8fef-71d60ed79103.png">
> 
> Here you are :))
> 
> I put a zip file below which has all app.js and other files you need.
> please ping me your result
> Goodluck.
> 
> [Archive.zip](https://github.com/githuboftigran/rn-range-slider/files/6851023/Archive.zip)

I have imported your files and then use in class-based component but still, the slider is not visible. I am not able to find the solution for it. Please see this: https://github.com/githuboftigran/rn-range-slider/issues/110

**Comment by aminsaedi** [comment]
First of all sorry for delay. these days I'm so busy.
```
import React, { Component } from "react";
import RangeSlider from "rn-range-slider";
import Thumb from "./Thumb";
import Rail from "./Rail";
import RailSelected from "./RailSelected";
import Label from "./Lable";
import Notch from "./Notch";

import { View } from "react-native";

class ClassSlider extends Component {
  state = { low: 0, high: 0 };
  handleValueChange = (low, high) => {
    // setLow(low);
    // setHigh(high);
  };
  render() {
    return (
      <View
        style={{
          flex: 1,
          backgroundColor: "#fff",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <RangeSlider
          style={{ width: 300, height: 10 }}
          min={0}
          max={100}
          step={1}
          floatingLabel
          renderThumb={(props) => <Thumb {...props} />}
          renderRail={(props) => <Rail {...props} />}
          renderRailSelected={(props) => <RailSelected {...props} />}
          renderLabel={(props) => <Label {...props} />}
          renderNotch={(props) => <Notch {...props} />}
          //   onValueChanged={handleValueChange}
        />
      </View>
    );
  }
}

export default ClassSlider;

```

I Also tries this in class component and it works with a simple change

<img width="475" alt="image" src="https://user-images.githubusercontent.com/23167933/126584887-64066386-1050-44ed-aec6-93c62653b8c4.png">

**Comment by Harsh2110mishra** [comment]
> First of all sorry for delay. these days I'm so busy.
> 
> ```
> import React, { Component } from "react";
> import RangeSlider from "rn-range-slider";
> import Thumb from "./Thumb";
> import Rail from "./Rail";
> import RailSelected from "./RailSelected";
> import Label from "./Lable";
> import Notch from "./Notch";
> 
> import { View } from "react-native";
> 
> class ClassSlider extends Component {
>   state = { low: 0, high: 0 };
>   handleValueChange = (low, high) => {
>     // setLow(low);
>     // setHigh(high);
>   };
>   render() {
>     return (
>       <View
>         style={{
>           flex: 1,
>           backgroundColor: "#fff",
>           alignItems: "center",
>           justifyContent: "center",
>         }}
>       >
>         <RangeSlider
>           style={{ width: 300, height: 10 }}
>           min={0}
>           max={100}
>           step={1}
>           floatingLabel
>           renderThumb={(props) => <Thumb {...props} />}
>           renderRail={(props) => <Rail {...props} />}
>           renderRailSelected={(props) => <RailSelected {...props} />}
>           renderLabel={(props) => <Label {...props} />}
>           renderNotch={(props) => <Notch {...props} />}
>           //   onValueChanged={handleValueChange}
>         />
>       </View>
>     );
>   }
> }
> 
> export default ClassSlider;
> ```
> 
> I Also tries this in class component and it works with a simple change
> 
> <img alt="image" width="475" src="https://user-images.githubusercontent.com/23167933/126584887-64066386-1050-44ed-aec6-93c62653b8c4.png">

Hey Amin, No issues. Thank you so much for your help.

**Comment by githuboftigran** [comment]
The slider works normally with expo. So closing this thread.
