### ISSUE TITLE
Add onChangeFinished prop

### ISSUE THREAD

**Issue by aminsaedi** [githuboftigran/rn-range-slider#106]
Hi.
i'm using this lib for a price range selector in my app. And i have to change my local states (minSelectedPrice&maxSelctedPrice) so it's drop performance of application.
it would be grate if there is a prop that will fire when user end changing the slider values.

**Comment by githuboftigran** [comment]
@aminsaedi , added onTouchStart and onTouchEnd events in version 2.1.0
