### ISSUE TITLE
Error on rendering in Modal components

### ISSUE THREAD

**Issue by aminsaedi** [githuboftigran/rn-range-slider#107]
I got this error when i put a Slider component in a Modal
`Invariant Violation: [10613,"RCTView",{"transform":[{"translateX":"<<NaN>>"}]}] is not usable as a native method argument`

**Comment by tinydiv333** [comment]
Did you find any solution?

**Comment by githuboftigran** [comment]
@aminsaedi , it works properly with modal. When you open an issue for a library, please provide code.

**Comment by roman-gula** [comment]
@aminsaedi try to add width to Slider component - for example
```
<RangeSlider
    style={{ width: '100%' }}
    ...
```
I also had this issue, when slider rendered with only thumb width, and when I clicked on it, error appeared.

@githuboftigran maybe make `width: '100%' ` by default for Slider with possibility set other width
