### ISSUE TITLE
Value is updating very slowly

### ISSUE THREAD

**Issue by Harsh2110mishra** [githuboftigran/rn-range-slider#109]
I have added RangeSlider in my app to take input value from the slider but its value is changing very slowly. Even I have a check on the console there also value is updating very slowly.

```
<RangeSlider
                            style={{ width: wp("88.89%"), height: 80 }}
                            gravity={"center"}
                            min={0}
                            max={500}
                            low={this.state.rangeLow}
                            high={this.state.rangeHigh}
                            step={1}
                            selectionColor="#3C5A5F"
                            blankColor="#E9E9E9"
                            thumbColor="#3C5A5F"
                            thumbBorderColor="#3C5A5F"
                            labelStyle={"none"}
                            onValueChanged={(low, high, fromUser) => {
                              this.setState({ rangeLow: low, rangeHigh: high });
                            }}
                          />

```

[![enter image description here][1]][1]

How can I solve this issue?

  [1]: https://i.stack.imgur.com/97DHu.gif

[https://i.stack.imgur.com/97DHu.gif](url)

**Comment by githuboftigran** [comment]
@Harsh2110mishra , looks like you are not using the latest version of this package.

**Comment by Harsh2110mishra** [comment]
I have also tried the latest version but the now-slider is not visible.  

[https://github.com/githuboftigran/rn-range-slider/issues/110](url)

**Comment by Harsh2110mishra** [comment]
> @Harsh2110mishra , looks like you are not using the latest version of this package.

I have also tried the latest version but the now-slider is not visible.
[https://github.com/githuboftigran/rn-range-slider/issues/url](url)
