### ISSUE TITLE
Conflict gesture on iOS navigation back

### ISSUE THREAD

**Issue by devswift2017** [githuboftigran/rn-range-slider#11]
You can see in video. Thanks
[Untitled.mov.zip](https://github.com/githuboftigran/rn-range-slider/files/3262917/Untitled.mov.zip)

**Comment by githuboftigran** [comment]
Will have a look on weekend.
I think `self.navigationController?.interactivePopGestureRecognizer?.isEnabled = false` on touch down will solve the issue.

**Comment by githuboftigran** [comment]
@devswift2017 , Didn't work. Tried some other things like `isExclusiveTouch` and even `hitTest: withevent:`
Nothing helped. I'm actually an android developer and don't have much experience with iOS.
Ordinary UISlider doesn't have that problem, but apple is too greedy to share the source code so I can't just read and understand how to do that.
If you find a solution or a library which doesn't have this problem, please let me know.
Won't close this issue yet.

**Comment by devswift2017** [comment]
@githuboftigran Yes , Thank for support. If I have any solution I'll make pull request resolve it.

**Comment by basbase** [comment]
If you are using react-navigation you can decrease the size of the back gesture area as a workaround:
`navigationOptions: { gestureResponseDistance: { horizontal: 15 } }}`

**Comment by devswift2017** [comment]
I had switch used modal stack navigator show up from bottom. And now is okay

**Comment by githuboftigran** [comment]
@devswift2017 , closing this issue
