### ISSUE TITLE
No way to prevent changing value by clicking anywhere on rail

### ISSUE THREAD

**Issue by ibrag474** [githuboftigran/rn-range-slider#111]
I use slider in a Flatlist and users change values accidentally by putting their finger on slider rails when scrolling. And there is no way to change this behaviour of slider.

**Comment by githuboftigran** [comment]
@ibrag474 , just published a new version: 2.2.1. Now slider captures touches when movement is more horizontal, than vertical (ratio is 2, so it will capture touches, if `dx ? 2 * dy`)
