### ISSUE TITLE
disableRange does not prevent highThumb from rendering

### ISSUE THREAD

**Issue by misbell** [githuboftigran/rn-range-slider#112]
had to use source code and comment out the rendering. It's supposed to do that, right? It's wrapped in a !disableRange flag.

**Comment by githuboftigran** [comment]
@misbell , can't reproduce this in version 2.2.1. You can try it in [demo app](https://github.com/githuboftigran/rn-widgets-demo).
And yes, `highThumb` is not rendered when `disableRange` is `true`.
