### ISSUE TITLE
detect thumb side touched

### ISSUE THREAD

**Issue by sokolovdm** [githuboftigran/rn-range-slider#113]
Is it possible to detect low or high  thumb was touched?

**Comment by githuboftigran** [comment]
@sokolovdm , yes it is, please read the documentation.

**Comment by sokolovdm** [comment]
Hmm
I saw only fromUser prop
Other props just return values
Sorry for my blindness

**Comment by jamieGardyn** [comment]
Low and high are given when a thumb is touched, but doesn't say which one is being touched.
