### ISSUE TITLE
Slider don't support Typescript

### ISSUE THREAD

**Issue by erinyesinfo** [githuboftigran/rn-range-slider#116]
Typing this:
> npm i --save-dev @types/rn-range-slider

Will result:
```
'@types/rn-range-slider@latest' is not in the npm registry.
You should bug the author to publish it (or use the name yourself!)
```
Can't wait to see it fix :)

Thank you,
Take care

**Comment by Luca8991** [comment]
While waiting for Typescript support, @dzbrozek created a declaration: https://github.com/githuboftigran/rn-range-slider/issues/74#issuecomment-756388927

**Comment by CapsAdmin** [comment]
I created a quick and dirty single file version of this project in typescript for react native 0.70.0. My goal was just to use it for some UI debugging.

https://gist.github.com/CapsAdmin/2220ceba796f7e9bef5af771b655e380

@githuboftigran feel free to use this if you decide to use Typescript. See the // NOTE: comments for things I observed.

**Comment by erinyesinfo** [comment]
Thank you for letting me know!

**Comment by githuboftigran** [comment]
Migrated to TS in version 2.2.1
