### ISSUE TITLE
Custom label

### ISSUE THREAD

**Issue by raajnadar-cb** [githuboftigran/rn-range-slider#118]
I want to use custom mapping instead of regular mapping something like

+1, 0, 1, 2, 3, 4, ..... 9, 10+

How can we do that? Didn't find any way to add custom labels.

**Comment by githuboftigran** [comment]
@raajnadar-cb , please check out `renderLabel` prop, it's a function which receives value from parameters and returns a react node. You can render any custom node based on `value` parameter.

**Comment by raajnadar-cb** [comment]
Can you add a simple example of how to use it? I also want it to return the same custom value so that I can store it in a local state.

**Comment by raajnadar-cb** [comment]
My requirement is something like this

<img width="296" alt="slider" src="https://user-images.githubusercontent.com/69234968/141642596-b2d11951-c6dd-4fe3-8ba5-b74baf236210.png">

The value above the slider is stored in the local state.
