### ISSUE TITLE
Why do we have to download additional files outside of the package to make this solution work? 

### ISSUE THREAD

**Issue by maxmiranda** [githuboftigran/rn-range-slider#119]
Appreciate the effort that went into this. But, genuinely curious why the npm package can't simply include, Thumb, Rail, RailSelected, Label, Notch etc. in it.

**Comment by githuboftigran** [comment]
@maxmiranda , because I wanted to keep the package as small as possible and because those components are just examples which may help you to create your own Thumb, rail, notch, etc. with your own design, not part of this package.
