### ISSUE TITLE
Sliding on Android doesn't work

### ISSUE THREAD

**Issue by byonghun** [githuboftigran/rn-range-slider#12]
On Android, the slider doesn't work as intended. The only way the range slider moves is by clicking. 
Works perfectly fine on iOS.

Can you help me resolve this?

Currently, I am on `react: ^16.6.0-alpha.8af6728` and `rn-range-slider: ^1.1.2`.

**Comment by githuboftigran** [comment]
@byonghun , please update `rn-range-slider` to version 1.2.4
If it doesn't help, please provide the code you are using.

**Comment by byonghun** [comment]
Thanks for your quick reply.

<img width="782" alt="Screen Shot 2019-06-10 at 10 09 35 PM" src="https://user-images.githubusercontent.com/37258789/59245205-80ae3300-8bcc-11e9-9294-892d09040c6b.png">

This is a screenshot of how I set it up.

I tried updating the version but once I updated the library, the range slider does not show where it's supposed to.

**Comment by githuboftigran** [comment]
@byonghun , the api was changed because of problems with setting high and low value. Please have a look.
Now there are no `lowValue` and `highValue` props anymore.
Instead you have methods `setHighValue` and `setLowValue` to set high and low values manually.
`this._rangeSlider.setLowValue(42);`
And also don't forget to unlink and link again rn-range-slider:
`react-native unlink rn-range-slider`
`react-native link rn-range-slider`

**Comment by byonghun** [comment]
Gotcha! I appreciate it, I'll give that a try.

**Comment by githuboftigran** [comment]
@byonghun , please close this issue if everything works.

**Comment by byonghun** [comment]
I've tried react-native unlink rn-range-slider and react-native link rn-range-slider and manually installing it but it still doesn't render the range slider. I've removed lowValue and highValue as well.

<img width="513" alt="Screen Shot 2019-06-10 at 11 19 59 PM" src="https://user-images.githubusercontent.com/37258789/59248112-53668280-8bd6-11e9-900a-c6f89a8e41b0.png">

**Comment by githuboftigran** [comment]
What do you mean by saying "doesn't render range slider"? Does it have fixed height? What's in rangeStyle? And what are the values of `min` and `duration`?

**Comment by byonghun** [comment]
It's empty where it's supposed to rendered.

My rangeStyle has height 20, width 250, and a marginTop 5.

Min is 0 and duration is 15

**Comment by byonghun** [comment]
Got it to work. I'll close the issue! Thanks!

I had to Link Binary with Libraries again.

@githuboftigran, appreciate your help!

**Comment by githuboftigran** [comment]
It's not empty.
There is a prop called `labelStyle`. Default value for it is `bubble`.
And it's not possible to draw a slider with bubble in 20pt height.
Try to set the height to 160 or something or change the `labelStyle ` to `none`.
Please read the README and go through all the props.
