### ISSUE TITLE
how to change step dynamicly

### ISSUE THREAD

**Issue by webstermobile** [githuboftigran/rn-range-slider#123]
0|-----------------50-----------------500------------------2500------------------|20000
the line is divided into four, but step is different,
how to realize this feature ?

**Comment by githuboftigran** [comment]
@webstermobile , I guess you should do some math in `renderValue` and in `onValueChange`.
like:
```
if (value < 5000) {
  value /= 100;
} else if (value < 10000) {
  value /= 20;
} else if (value < 15000) {
  value /= 6
}
```
