### ISSUE TITLE
Is there a way to show labels all the time?

### ISSUE THREAD

**Issue by endrits079** [githuboftigran/rn-range-slider#126]
Labels are shown only when moving the slider, is it possible to make them show all the time?

**Comment by andrebordignon-foodtosave** [comment]
any lucky here?

**Comment by endrits079** [comment]
> any lucky here?

in the readme file there is the 
"A special section about permanent labels." where they mentioned that they will never be implementing that feature. But you can use Text Components and show the values yourself
