### ISSUE TITLE
How to add current value in middle of range

### ISSUE THREAD

**Issue by jamieGardyn** [githuboftigran/rn-range-slider#127]
We have a low and a high value (min max) but is there anyway to have a render for the current value?

for instance...

min={1}
max={15}
value={10}

**Comment by githuboftigran** [comment]
@jamieGardyn , no... If we pass the value with props (like in `TextInput` for example), we would have to rerender every time a value is changed. This package is designed to be as fast as possible, with minimum rerenders.

**Comment by jamieGardyn** [comment]
Ok - but just fyi - my goal actually is for it to re-render every time the value changes.
