### ISSUE TITLE
[Suggestion] alwaysShowLabels prop

### ISSUE THREAD

**Issue by nightness** [githuboftigran/rn-range-slider#129]
I'd like to first say, thanks to the contributers. This is the ONLY slider component I will use for React Native! My suggestion is to allow labels to always be visible. I made some progress toward this goal, but I'm not sure how to initialize the labels outside of PanResponder. If anyone has any ideas how to do this, please fork my fork, and PR or please describe to me a path forward.

https://github.com/nightness/rn-range-slider

[Demo Video (YouTube)](https://youtu.be/nv1OOGLLENg)

**Comment by githuboftigran** [comment]
@nightness , thanks for support!
There is a section in README about this.
https://github.com/githuboftigran/rn-range-slider#a-special-section-about-permanent-labels
