### ISSUE TITLE
UI scale when rolate device iOS

### ISSUE THREAD

**Issue by devswift2017** [githuboftigran/rn-range-slider#13]
When used style={{width: "100%",: 40}}.
and rolate device, I have issue UI.
[report Issue relate device.mov.zip](https://github.com/githuboftigran/rn-range-slider/files/3317113/report.Issue.relate.device.mov.zip)

**Comment by githuboftigran** [comment]
@devswift2017 , Will have a look

**Comment by devswift2017** [comment]
you have plan for fix it?

**Comment by githuboftigran** [comment]
@devswift2017 , yes, will fix it in this weekend.

**Comment by githuboftigran** [comment]
@devswift2017 fixed in 1.2.5

**Comment by devswift2017** [comment]
Thanks so much :)
