### ISSUE TITLE
Have problem after install package

### ISSUE THREAD

**Issue by serveyk0-work** [githuboftigran/rn-range-slider#131]
Module parse failed: Unexpected token (32:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const falseFunc = () => false;
| 
> export interface SliderProps extends ViewProps {
|   min: number;
|   max: number;
[
<img width="1411" alt="Screenshot 2022-09-15 at 17 28 08" src="https://user-images.githubusercontent.com/78041681/190430308-ad36e273-d55c-4de9-9c20-12a87694c658.png">
](url)

**Comment by githuboftigran** [comment]
@serveyk0-work , not sure what's the cause of the issue, it may be older version of react native, ts config, webpack config, babel, etc.
The module uses typescript now, so it has to be supported by the project.
With fresh app everything works properly.
Check out this repo:
https://github.com/githuboftigran/rn-widgets-demo
