### ISSUE TITLE
Execution failed for task ':rn-range-slider:verifyReleaseResources'.

### ISSUE THREAD

**Issue by matheus-rosin** [githuboftigran/rn-range-slider#17]
Hi!

I'm trying to generate an apk of my app; but then that fails with the message:

```
> Task :rn-range-slider:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rn-range-slider:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  [PROJECT_ROOT]/node_modules/rn-range-slider/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  [PROJECT_ROOT]/node_modules/rn-range-slider/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  [PROJECT_ROOT]/node_modules/rn-range-slider/android/build/intermediates/res/merged/release/values/values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  [PROJECT_ROOT]/node_modules/rn-range-slider/android/build/intermediates/res/merged/release/values/values.xml:2715: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

Am I making something wrong?

Thanks in advance! 😸

**Comment by rajeshmarotu** [comment]
I encountered same problem too.
Solved the issue ? @matheus-rosin

**Comment by githuboftigran** [comment]
Not yet. Facebook changed the api and now libs should be autolinked, but they are not.
And I couldn't find a normal tutorial about how to make your own auto-linkable library.

**Comment by usamamoinakhter** [comment]
Is there anyway to manually fix this?

**Comment by usamamoinakhter** [comment]
> Is there anyway to manually fix this?

Building the application with android studio fixed it for me.

**Comment by githuboftigran** [comment]
Updated the lib and tested for react-native 0.61.1, everything works as expected (for both android and ios).
For iOS there is an extra step: `cd ios && pod install`
For android everything works out of the box, just add the package and run `react-native run-android`
So closing this issue.
