### ISSUE TITLE
it will not working on Android if you does not set height in style property. why?

### ISSUE THREAD

**Issue by nguyenap** [githuboftigran/rn-range-slider#18]

**Comment by githuboftigran** [comment]
@nguyenap , because I was too lazy and didn't add support for automatic height calculation inside the view (so it can wrap it's content by default).
Will try to find time and fix it in this weekend ;-)
Thanks for reporting!

**Comment by githuboftigran** [comment]
I'm reopening this issue if you don't mind. Open issue will add some additional motivation to do that.

**Comment by nguyenap** [comment]
ok good. Hope it will be completed soon :)

**Comment by genesy** [comment]
Is this the reason I can't drag the sliders on android? or is that a different issue?

**Comment by githuboftigran** [comment]
@genesy , is your slider in a scrollable component? There is a similar [open issue](https://github.com/githuboftigran/rn-range-slider/issues/20), I can't figure out why is it happening.

**Comment by genesy** [comment]
yeah i figured it out just now. it was in react-native-modal and i had to
turn of it's swiping capabilities on android. works fine on ios tho

**Comment by dev-sathish** [comment]
The slider is not working for android. it shows Android not supported yet? even if we set both height and width in style props.

**Comment by githuboftigran** [comment]
@dev-sathish 
> it shows Android not supported yet?
Nope, it doesn't show "Android not supported yet".
And it IS working on android. Just follow the instructions in readme (link for react-native < 60, unlink for react-native >=60, styles, etc).
