### ISSUE TITLE
iOS app crashing

### ISSUE THREAD

**Issue by infaz** [githuboftigran/rn-range-slider#2]
when I set lowValue and highValue iOS app is getting crashed

**Comment by erdemildiz** [comment]
+1

**Comment by erdemildiz** [comment]
@githuboftigran Could you help?

**Comment by githuboftigran** [comment]
@infaz , could you please send crash log and component JSX?

**Comment by githuboftigran** [comment]
I updated this component. The api is changed so you won't have this crash anymore.
