### ISSUE TITLE
Slider inside ScrollView is not smooth in both iOS and Android

### ISSUE THREAD

**Issue by shivamtiwari8736** [githuboftigran/rn-range-slider#20]
Sliding in iOS and Android is not smooth. It leaves thumb while scrolling. I have taken Range Slider inside ScrollView. On top there is Range Slider and after that a list from API. When there is less items that no scroll needed, Range Slider works with absolute beauty. But when there is enough data in list that makes scroll view to scroll, the problem Occurs on both android and iOS.

**Comment by githuboftigran** [comment]
@shivamtiwari8736 , thanks for reporting. I will have a look on this weekend.

**Comment by shivamtiwari8736** [comment]
Hi @githuboftigran , Any update buddy?

**Comment by githuboftigran** [comment]
@shivamtiwari8736 , sorry dude, couldn't find some time on this weekend... I will add a comment here when I find the problem

**Comment by shikhawebvillee** [comment]
@githuboftigran, Any update on this issue?

**Comment by githuboftigran** [comment]
@shikhawebvillee , nope... I asked some developers, they couldn't help

**Comment by ChandanCBL** [comment]
Facing the same issue. Anyone found the solution for this ?

**Comment by DanielMalak** [comment]
For those having the same issue you can use the onTouchStart and the onTouchEnd functions to enable and disable the scrollview
this is my implementation 
    this.state = {
      allowScroll:true,
}
        <ScrollView scrollEnabled={this.state.allowScroll}>

          <RangeSlider
          min={10}
          max={1000}
          step={10}
          onTouchStart={()=>{this.setState({allowScroll:false})}}
          onTouchEnd={()=>{this.setState({allowScroll:true})}}/>
        </ScrollView>

**Comment by githuboftigran** [comment]
@shivamtiwari8736 , @DanielMalak @ChandanCBL @shikhawebvillee , just published v2. Now [PanResponder](https://reactnative.dev/docs/panresponder/) is used for touches. Is this issue still in there?

**Comment by haruhiroYakumo** [comment]
There is one more thing that I recommend. If you are using some state management library like redux, do not update store from onValueChanged function. It slows down the system a lot. Instead, it's performance-wise to launch update function from onTouchEnd function.

**Comment by Great-hijack** [comment]
How can we implement this with v2?

**Comment by KingDoxik** [comment]
I have similar problem, but in modal using React Navigation on iOS. I was not able to find any way to temporarily disable the swipe to dismiss.

**Comment by mrshahzeb7** [comment]
it was not smooth in scrollView for me ,while moving slider scroll starts to move! (especially iOS) 
I solved it by scrollview property "disableScrollViewPanResponder={true}"

**Comment by githuboftigran** [comment]
Hey all, just published a new version: 2.2.1. Now slider captures touches when movement is more horizontal, than vertical (ratio is 2, so it will capture touches, if dx ? 2 * dy)
