### ISSUE TITLE
Handle event start touchable change and end Touchable change event

### ISSUE THREAD

**Issue by devswift2017** [githuboftigran/rn-range-slider#22]

**Comment by devswift2017** [comment]
I thing you need add event when begin touch change value and end event when user finish change. My project http://passionui.com/ have used your component. and I want listen event for action begin and end change value range for disable scrollview

**Comment by githuboftigran** [comment]
@devswift2017 good point, will add today or tomorrow

**Comment by devswift2017** [comment]
yeah thanks :)

**Comment by githuboftigran** [comment]
Published 1.2.7 with `onTouchStart` and `onTouchEnd` events.
Please add a comment in this thread in case of any problem.
