### ISSUE TITLE
Is it possible for the min and max for the slider to both be the same value?

### ISSUE THREAD

**Issue by victor-z-xiong** [githuboftigran/rn-range-slider#26]
Right now, when I have the slider this is the narrowest I can get the two points to move

![image](https://user-images.githubusercontent.com/31559004/67456481-bbe25900-f5e5-11e9-90c6-2fe892ffdfb1.png)

However, shouldn't I be able to have the two points point to the same value as well, so that max == min?

**Comment by githuboftigran** [comment]
Done
