### ISSUE TITLE
hideLabels, maxLabelColour and minLabelColour doesn't work.

### ISSUE THREAD

**Issue by alecpo** [githuboftigran/rn-range-slider#29]
I tested in Iphone 6s Plus simulator and android 9 physical device and this props didn't work.
See my Slider component:

```
<StyledRangeSlider
            hideLabels={true}
            maxLabelColour='#555555'
            ref={RangeSliderRef}
            gravity='center'
            min={minValue}
            max={maxValue}
            step={(maxValue - minValue) * 0.05}
            selectionColor={COLORS.primary}
            blankColor={COLORS.lightGrayBackground}
            onValueChanged={(low, high) => {
              onChangeMinSliderValue(low);
              onChangeMaxSliderValue(high);
            }}
 />
```

```
const StyledRangeSlider = styled(RangeSlider)`
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 80;
  margin-top: -35;
  margin-bottom: 5;
`;
```

the both property doesn't work, see the image:

<img src="https://user-images.githubusercontent.com/20051865/68166155-3abd8700-ff40-11e9-8f41-5c6b9bf828af.png" width=300>

Any suggestion?

**Comment by githuboftigran** [comment]
@alecpo , which props?

**Comment by alecpo** [comment]
Sorry guys I'm doing a mass, there is a library really close to this one where I was looking the documentation and being confusing. I will close this issue.
