### ISSUE TITLE
Reset thumb to default

### ISSUE THREAD

**Issue by Saad-Bashar** [githuboftigran/rn-range-slider#3]
Is there a way we can reset the thumb again to min and max default value when a button is pressed?

**Comment by erdemildiz** [comment]
+1

**Comment by githuboftigran** [comment]
@Saad-Bashar, slider doesn't remember thumb positions and doesn't actually have default values.
So if you have default values for slider, you probably should add high and low props to slider if the button is pressed like this:
```
render() {
...
const defValues = this.state.buttonPressed ? {low: _defaultLow, high: _defaultHigh} : {}
...
<RangeSlider
...
{...defValues}
>
...
```

**Comment by githuboftigran** [comment]
Updated the api, added methods to set high and low values.
