### ISSUE TITLE
1.3.0 does not work on RN <0.60

### ISSUE THREAD

**Issue by rafalzawadzki** [githuboftigran/rn-range-slider#30]
Due to this commit: https://github.com/githuboftigran/rn-range-slider/commit/fc2594c94500fdc4ca1d4360150c8d5b4c8c35b4

Android build fails, because androidx deps are missing.

A workaround for now (for <0.60) is to locally replace

```
import androidx.annotation.Nullable;
import androidx.core.view.ViewCompat;
```

with

```
import android.support.annotation.Nullable;
import android.support.v4.view.ViewCompat;
```

**Comment by githuboftigran** [comment]
@rafalzawadzki aaah, right... and with support lib it doesn't work on RN > 0.60 and you have to `migrate to androidX` from android studio

**Comment by githuboftigran** [comment]
@rafalzawadzki , did it work?

**Comment by rafalzawadzki** [comment]
@githuboftigran I decided to just use my workaround for the time being. We are upgrading RN soon anyways ;)

**Comment by bilsak18** [comment]
It's sad how we have to work the issue around in such a non-proper way. Some people are still using lower versions of react-native, which makes it inappropriate for them to migrate to androidx yet :/
