### ISSUE TITLE
Publish new version with type definitions

### ISSUE THREAD

**Issue by peterkuiper** [githuboftigran/rn-range-slider#32]
Since https://github.com/githuboftigran/rn-range-slider/pull/28 has been merged, is it possible to publish a new version?

**Comment by peterkuiper** [comment]
Btw, it seems that prop validation and type is missing for the `style` prop.

**Comment by peterkuiper** [comment]
@githuboftigran Could you perhaps publish a new version? I could open a PR for the validation of the style prop before publishing the new version.

**Comment by githuboftigran** [comment]
@peterkuiper published 1.3.1
