### ISSUE TITLE
Doesn't work on Expo Cli

### ISSUE THREAD

**Issue by clu7ch3r** [githuboftigran/rn-range-slider#33]
Getting this error. Have anyone managed to get it to work on expo?

![image](https://user-images.githubusercontent.com/36937310/69411808-e568d000-0cca-11ea-87ea-44ca43cf712c.png)

**Comment by robertwilliamallen** [comment]
Same issue here.

**Comment by gr0x0** [comment]
Any news?

**Comment by githuboftigran** [comment]
@clu7ch3r , @robertwilliamallen , @gr0x0 , won't fix this as I'm not using expo. I prefer using react native cli, build project on my machine and don't take Expo seriously.

**Comment by clu7ch3r** [comment]
@githuboftigran Well at least save developers time by warning that it doesn't work with expo.

**Comment by githuboftigran** [comment]
@clu7ch3r , there is already a line in known issues :)

**Comment by clu7ch3r** [comment]
@githuboftigran Wdym? I'm talking about on the doc that you should state that it's not compatible with expo.

**Comment by githuboftigran** [comment]
@clu7ch3r I mean Known issues section of readme doc
![image](https://user-images.githubusercontent.com/4550976/78987094-0cbb1f00-7b3e-11ea-810b-35e8b8461ce8.png)

**Comment by clu7ch3r** [comment]
@githuboftigran That's all the way at the bottom though. By the time they reach to it which most won't read an entire doc, they'll most likely be too invested to turn back.

**Comment by githuboftigran** [comment]
@clu7ch3r, that's why you should **always** read the documentation and scroll to known issues section before using a library :)
Hope this case will help you to be more attentive to readme files and documentations in future.

**Comment by clu7ch3r** [comment]
@githuboftigran You missed the other half of what I've said but ok, was just giving suggestions to prevent future frustrations.

**Comment by doomevaristo** [comment]
@githuboftigran I've read the documentation and there is no mentioning of the event "onTouchEnd" for example, but it exists and it works perfectly (tried 3 hole days making this behavior myself before knowing this was already a thing). So what is the point of reading a documentation that is not reliable?

**Comment by githuboftigran** [comment]
@doomevaristo , `onTouchEnd` doesn't work properly. The library [passes all additional props to root view](https://github.com/githuboftigran/rn-range-slider/blob/1f8a079ad11003848f66125a5e71a2facd2101d4/index.js#L173), so it's a View prop.
Slider uses pan handlers and other touch handlers shouldn't be used.

Don't know why do you need it and why it works for you, but passing `onTouchEnd` breaks the component on emulator.
