### ISSUE TITLE
We need onComplete instead onValueChanged

### ISSUE THREAD

**Issue by humanyu** [githuboftigran/rn-range-slider#37]
Hi there, 
onValueChanged setState on every move. But I need setState on complete pointer.

Please help me out

**Comment by githuboftigran** [comment]
@humanyu , there are 2 callbacks: `onTouchStart` and `onTouchEnd`.
You can update your view in those callbacks. For example in `onValueChanged` set current value to class field (not state variable): `this.sliderValue = highValue`;
And in `onTouchEnd`, set the value in state: `this.setState({ sliderValue: this.sliderValue })`

Closing this issue as it's not actually an issue.

**Comment by kamlesh1000** [comment]
"onTouchStart"method is called but "onTouchEnd" method is not called when the slider is rapidly moved verticle.

**Comment by sujatha2016** [comment]
What about the same when it is added inside a functional component ?
