### ISSUE TITLE
Range Slider diaplays wrong value when max value is more than or equal to 10000000000 in IOS

### ISSUE THREAD

**Issue by ppv94** [githuboftigran/rn-range-slider#38]
`"react-native": "0.61.5",
"rn-range-slider": "^1.3.0"`

**I am using rn-range-slider in my application, It works fine in android but in IOS when the value is more than or equal to 10000000000 is displaying the wrong value in the label, But when we slide in onValueChanged I am getting correct value of slide point.**

minValue: 108174, maxValue: 2856400000 It shows minus values in as shown in below image. 

![Screen Shot 2020-01-27 at 11 21 11 AM](https://user-images.githubusercontent.com/28724702/73152781-2c25dc80-40f7-11ea-9376-09877f883726.png)

if minValue: 108174, maxValue: 285640000 It shows correct value in lable in as shown in below image.  

![Screen Shot 2020-01-27 at 11 24 11 AM](https://user-images.githubusercontent.com/28724702/73152885-95a5eb00-40f7-11ea-9237-96653c6fa862.png)

**It works fine in android but it shows wrong value in label in IOS.**

**Comment by githuboftigran** [comment]
@ppv94 , just fixed in 1.3.1
