### ISSUE TITLE
[v1.3.1] JSON value '0' of type NSNumber cannot be converted to NSString

### ISSUE THREAD

**Issue by ahce** [githuboftigran/rn-range-slider#43]
### It only happens on iOS.

![image](https://user-images.githubusercontent.com/12452003/77291857-cbadb880-6cbd-11ea-8b21-857e1f392106.png)

### Environment

- react 16.9.0
- react-native 0.61.5

**Comment by githuboftigran** [comment]
@ahce , you probably forgot to rebuild the application after upgrading to 1.3.1, because all values passed to native views are Strings in 1.3.1.

**Comment by ahce** [comment]
@githuboftigran Sorry for my mistake, rebuilding works fine!
