### ISSUE TITLE
Could not increment time 

### ISSUE THREAD

**Issue by Shruthyshanthraj** [githuboftigran/rn-range-slider#49]
I can not increment time as I move range using sliders. I always get Thu Jan 01 1970 05:30:00 GMT+0530 (India Standard Time) on value changed. Can someone help me on this?

**Comment by githuboftigran** [comment]
v2 uses only numbers and `renderLabel` prop, so to use it for time values you can simply set `min` and `max` to time milliseconds and render your own label component which takes time milliseconds in props and renders what's needed.
