### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by Marzdor** [githuboftigran/rn-range-slider#50]
Is there anyway to disable the label or are we required to use it?

I tried `labelStyle={'none'}` but it still shows the label.

**Comment by t-perun** [comment]
`labelStyle="none"` works for me

**Comment by dev-sathish** [comment]
how to make the label visible? Not only when the value is changing?

**Comment by githuboftigran** [comment]
@Marzdor `labelStyle={'none'}` is working, please make sure you are using the last version.
