### ISSUE TITLE
Make corner radius

### ISSUE THREAD

**Issue by angebizzinfotech** [githuboftigran/rn-range-slider#52]
![Simulator Screen Shot - iPhone X - 2020-05-02 at 13 01 05](https://user-images.githubusercontent.com/28722844/80858189-4bdc1c00-8c75-11ea-8be9-69cffa026274.png)

Hello,
I have attached screenshot in that I need to give corner-radius to green square. Can you please let me know how should I make those both square circular with given radius.

Thank You

**Comment by githuboftigran** [comment]
v2 uses render props, so now you can render any custom view.
