### ISSUE TITLE
Invariant Violation:requireNativeComponent "RangeSlider was not found in the UIManager" in android??

### ISSUE THREAD

**Issue by sangampokharel** [githuboftigran/rn-range-slider#53]
"react-native": "0.62.2"
 "rn-range-slider": "^1.3.2"

import RangeSlider from 'rn-range-slider';

                                <RangeSlider
                                    style={{ width: 160, height: 80 }}
                                    gravity={'center'}
                                    min={200}
                                    max={1000}
                                    step={20}
                                    selectionColor="#3df"
                                    blankColor="#f618"
                                    onValueChanged={(low, high, fromUser) => {
                                        this.setState({ rangeLow: low, rangeHigh: high })
                                    }} />

**Comment by githuboftigran** [comment]
@sangampokharel , run yarn install and cd ./ios && pod install and rebuild project for both platforms after updating the version.
