### ISSUE TITLE
Invariant violation: requireNativeComponent: "RangeSlider" was not found in the UIManager, in iOS and android

### ISSUE THREAD

**Issue by bravemaster619** [githuboftigran/rn-range-slider#54]
> Invariant Violation: requireNativeComponent: "RangeSlider" was not found in the UIManager.
This error is located at:
    in RangeSlider (at rn-range-slider/index.js:57)
    in RangeSlider (at browse.tsx:125)
    in RCTView (at browse.tsx:124)
    in RCTView (at browse.tsx:79)
    in Browse (at SceneView.tsx:121)
   
React Native: 0.62.2
rn-range-slider: 1.3.2
Platform: iOS and android

Example code:
```javascript
<View style={{ flex: 1 }}>
  <RangeSlider
    min={1}
    max={100}
    onValueChanged={(low, high, value) => {
      setDistance(value);
    }}
  />
</View>
```

**Comment by bravemaster619** [comment]
Restarting Metro server will solve the problem

#53

**Comment by abdulrahman18** [comment]
I am using expo and typescript. Still, I am getting this issue
