### ISSUE TITLE
how to support rtl ?

### ISSUE THREAD

**Issue by AhmedHF** [githuboftigran/rn-range-slider#56]

**Comment by githuboftigran** [comment]
@AhmedHF , what exactly do you mean?

**Comment by shareef-dweikat** [comment]
I think this link will help
https://github.com/githuboftigran/rn-range-slider/issues/76

**Comment by githuboftigran** [comment]
@AhmedHF , as mentioned @shareef-dweikat, this thread is probably what you need:
https://github.com/githuboftigran/rn-range-slider/issues/76
So closing this issue.
