### ISSUE TITLE
Xcode not compiling: "library not found for -lRangeSlider"

### ISSUE THREAD

**Issue by afouchet** [githuboftigran/rn-range-slider#57]
Hello,
I use 
react-native 0.61.5 
rn-range-slider 1.3.2
xcode 11.3.1

I did "npm install", "react-native link", "pod install".
I did Product/Clean, Product/Clean build folder

But, when I try to build, I get the error
"library not found for -lRangeSlider"

Do you have an idea why is that ?

**Comment by Rahulv2492** [comment]
@afouchet it might be some linking issue. Try manual linking

**Comment by githuboftigran** [comment]
v2 doesn't use any additional native modules so you won't have any linking issues anymore.
