### ISSUE TITLE
How to set visible label after selection? 

### ISSUE THREAD

**Issue by tinydiv333** [githuboftigran/rn-range-slider#58]
I really like your library, recently i have implemented this in my project and i want to set label always visible how can i achieve this functionality?

**Comment by githuboftigran** [comment]
There is no way to do that as it's a bad UI/UX. I added a special section in v2's readme, please have a look.

**Comment by tareksmoubarak** [comment]
> I really like your library, recently i have implemented this in my project and i want to set label always visible how can i achieve this functionality?

Same here :S
