### ISSUE TITLE
no such file or directory: 'libRNRangeSlider.a'

### ISSUE THREAD

**Issue by erdemildiz** [githuboftigran/rn-range-slider#6]
I am getting this error to build for archive. I tried everything, but ı couldn't find any solition. 

```no such file or directory: '/Users/erdemildiz/Library/Developer/Xcode/DerivedData/fixbilet-ciqtvxssenduvsewflchltgqhclh/Build/Intermediates.noindex/ArchiveIntermediates/fixbilet/BuildProductsPath/Release-iphoneos/libRNRangeSlider.a'```

**Comment by githuboftigran** [comment]
Did you run `react-native link rn-range-slider` ?

**Comment by devswift2017** [comment]
I'm have same issue, when release app. buid fail, debug version is normal

**Comment by devswift2017** [comment]
clang: error: no such file or directory: '/Users/huynhdung/Library/Developer/Xcode/DerivedData/FelixPro-cwvyxzrdwkbtwgebcudzmwwwxgua/Build/Intermediates.noindex/ArchiveIntermediates/FelixPro/BuildProductsPath/Release-iphoneos/libRNRangeSlider.a'

**Comment by devswift2017** [comment]
![image](https://user-images.githubusercontent.com/27657751/57081253-8d628000-6d1e-11e9-9c98-6f70ea7a4c77.png)

**Comment by erdemildiz** [comment]
+1

**Comment by mayankgarg056** [comment]
I am facing same problem, Please resolve this

**Comment by githuboftigran** [comment]
![image](https://user-images.githubusercontent.com/4550976/58762276-8918c500-855f-11e9-9e6b-22c03a005fe8.png)

I found the answer in stackoverflow:
https://stackoverflow.com/questions/14947139/xcodebuild-failure-clangerror-no-such-file-or-directory

This worked for me.

This question may also be useful if you get an error like:
`'React/RCTBridgeModule.h' file not found`

https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found

**Comment by christopherdcunha** [comment]
FYI @erdemildiz @devswift2017 @mayankgarg056 - PR #9 should fix your bug, but you can use this work around if it doesn't get merged:

Update `package.json` such that:
```json
{
...
  "postinstall": "... && sed -i.bak -e 's/IPHONEOS_DEPLOYMENT_TARGET = 12.1;/IPHONEOS_DEPLOYMENT_TARGET = 9.0;/g' ./node_modules/rn-range-slider/ios/RNRangeSlider.xcodeproj/project.pbxproj",
...
}
```

Once this is done, you can run `yarn` or `npm install` and the `IPHONEOS_DEPLOYMENT_TARGET` will be patched to 9.0

**Comment by devswift2017** [comment]
@christopherdcunha  thanks so much

**Comment by githuboftigran** [comment]
@christopherdcunha , merged. Thanks for helping!
