### ISSUE TITLE
Can you help me to reset the slider value?

### ISSUE THREAD

**Issue by selva21kd** [githuboftigran/rn-range-slider#63]
Hi,

It was an amazing component, helpful. I need to know how to reset the selected range value into default value. is this possible?

**Comment by shayan1998** [comment]
i have the same problem

**Comment by irosenzw** [comment]
same problem here

**Comment by irosenzw** [comment]
> Hi,
> 
> It was an amazing component, helpful. I need to know how to reset the selected range value into default value. is this possible?

You can use `ref` :
https://github.com/githuboftigran/rn-range-slider#methods

**Comment by githuboftigran** [comment]
I'm working on version 2 which will be a pure JS component with Animated api. So I don't update this version anymore.

**Comment by githuboftigran** [comment]
And yes, you can use setLowValue, setHighValue methods, please read the Readme file.

**Comment by irosenzw** [comment]
@shayan1998 @selva21kd until version 2.0 will be published, if you are having some trouble you can use `setHighValue` and `setLowValue` like this:
```React
const myComponent = () => {
  ...
  const sliderRef = React.useRef(null);
  ...
  const resetSlider = () => {
    sliderRef?.current.setLowValue(0);
    sliderRef?.current.setHighValue(10);
  }

  return (
    <RangeSlider
       ref={sliderRef}
       ...
     />
  )
   .....
}
```

**Comment by shayan1998** [comment]
> @shayan1998 @selva21kd until version 2.0 will be published, if you are having some trouble you can use `setHighValue` and `setLowValue` like this:
> 
> ```
> const myComponent = () => {
>   ...
>   const sliderRef = React.useRef(null);
>   ...
>   const resetSlider = () => {
>     sliderRef?.current.setLowValue(0);
>     sliderRef?.current.setHighValue(10);
>   }
> 
>   return (
>     <RangeSlider
>        ref={sliderRef}
>        ...
>      />
>   )
>    .....
> }
> ```

thank you. that's solve my problem

**Comment by githuboftigran** [comment]
@selva21kd , @shayan1998 , just released v2 of the library. To set the value you can simply pass `low` / `high` props.
