### ISSUE TITLE
Want to Add Size Slider

### ISSUE THREAD

**Issue by ladaniavadh** [githuboftigran/rn-range-slider#66]
Hello,
I want to add size slider like XXS to XXL and in tooltip same will be shown line S, M, L etc.

is there any way to add the slider like this?

**Comment by githuboftigran** [comment]
In v2 you can pass a `renderLabel` prop which can render anything you need.
So to achieve this you need sizes mapped to numbers like:
`const sizes = ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL' ];`
Set `min={0} max={sizes.length - 1}`
And draw the label:
`renderLabel={value => <Label text={sizes[value]}/>}`

Your custom label component should get the text property and show it in a balloon or whatever it renders.
