### ISSUE TITLE
[v2] Slider gets stuck when low and high values ​​are 0

### ISSUE THREAD

**Issue by ahce** [githuboftigran/rn-range-slider#69]
Hi!

This issue happens because the low thumb is always over the high thumb.
v1 doesn't have this issue.

#### Code sample
- https://snack.expo.io/@ahce/rn-range-slider-bug

**Comment by githuboftigran** [comment]
@ahce , will fix

**Comment by githuboftigran** [comment]
@ahce , fixed, please check out v2.0.3
