### ISSUE TITLE
[V2] onPress methods do not work when rendering a TouchableOpacity as a thumb

### ISSUE THREAD

**Issue by Cristi6** [githuboftigran/rn-range-slider#72]
Hi, what I am trying to do is to simulate a fromUser on onValueChanged from v1, setting a fromUser local state on onPressIn on a TouchableOpacity (which is rendered as a thumb) but the onPressIn/onPress/onPressOut events do not trigger. And idea why or how can I work around this?

**Comment by githuboftigran** [comment]
@Cristi6 , I'll publish a new version in next few days. Will add those listeners.

**Comment by githuboftigran** [comment]
@Cristi6 , just published 2.0.3. Didn't add listeners, but added `fromUser` parameter to `onValueChanged`
