### ISSUE TITLE
[v2] Thumbs don't update when low or high values are changed

### ISSUE THREAD

**Issue by ahce** [githuboftigran/rn-range-slider#73]
Hi!

This issue happens because [prop and ref](https://github.com/githuboftigran/rn-range-slider/blob/master/index.js#L67) values are always equals

#### Code sample
- https://snack.expo.io/@ahce/rn-range-slider-bug2

**Comment by Donhv** [comment]
same issue

**Comment by ZooTopiaGG** [comment]
same issue, please solved it

**Comment by githuboftigran** [comment]
Fixed in version [2.0.4](https://www.npmjs.com/package/rn-range-slider/v/2.0.4)
