### ISSUE TITLE
Would you like to apply for TypeScript?

### ISSUE THREAD

**Issue by leechanghoon3024** [githuboftigran/rn-range-slider#74]
I wonder if you have any plans to support Typescript in the future.

any plans like this?

**Comment by githuboftigran** [comment]
@leechanghoon3024 , don't think so. This is a small package and I think pure JS is enough for it.

**Comment by dzbrozek** [comment]
for those looking for typescript types

```
declare module 'rn-range-slider' {
  import * as React from 'react';
  import { ViewStyle } from 'react-native';

  interface RangeSliderProps {
    min: number;
    max: number;
    step: number;
    low?: number;
    high?: number;
    floatingLabel?: boolean;
    disableRange?: boolean;
    disabled?: boolean;
    allowLabelOverflow?: boolean;
    renderThumb: () => JSX.Element;
    renderRail: () => JSX.Element;
    renderRailSelected: () => JSX.Element;
    renderLabel?: (value: number) => JSX.Element;
    renderNotch?: () => JSX.Element;
    onValueChanged?: (low: number, high: number, fromUser: boolean) => void;
    style?: ViewStyle;
  }

  export default class RangeSlider extends React.Component<RangeSliderProps> {}
}
```

**Comment by gabrielmoncea** [comment]
@dzbrozek  This should be linked in the docs at least

> for those looking for typescript types
> 
> ```
> declare module 'rn-range-slider' {
>   import * as React from 'react';
>   import { ViewStyle } from 'react-native';
> 
>   interface RangeSliderProps {
>     min: number;
>     max: number;
>     step: number;
>     low?: number;
>     high?: number;
>     floatingLabel?: boolean;
>     disableRange?: boolean;
>     disabled?: boolean;
>     allowLabelOverflow?: boolean;
>     renderThumb: () => JSX.Element;
>     renderRail: () => JSX.Element;
>     renderRailSelected: () => JSX.Element;
>     renderLabel?: (value: number) => JSX.Element;
>     renderNotch?: () => JSX.Element;
>     onValueChanged?: (low: number, high: number, fromUser: boolean) => void;
>     style?: ViewStyle;
>   }
> 
>   export default class RangeSlider extends React.Component<RangeSliderProps> {}
> }
> ```

**Comment by getterhiss** [comment]
@dzbrozek Awesome, thank you!!
