### ISSUE TITLE
Set initial/start value

### ISSUE THREAD

**Issue by jovanialferez** [githuboftigran/rn-range-slider#75]
Is is possible to set initial value? Let say i have setup the slider with `min` 0 and `max` 50 with `disableRange`, but initially i wanted to show slider with position already at max value. Or maybe at a position between the range. Thanks!

**Comment by jovanialferez** [comment]
I tried setting `low` equal to the `max` value, but it wont allow me to drag slider to any value then.

**Comment by joseomar10** [comment]
Hi! Any solutions ?

**Comment by jovanialferez** [comment]
@joseomar10 i decided to use another library -- https://github.com/ptomasroos/react-native-multi-slider

**Comment by githuboftigran** [comment]
@jovanialferez , I can't reproduce this issue. Maybe you were using an old version. In current version you just need to set low prop to the max value (or any other value between low and high) initially, then update it on onValueChange callback.
