### ISSUE TITLE
How to reverse thumb positions? i need min on right, and max on left.

### ISSUE THREAD

**Issue by shareef-dweikat** [githuboftigran/rn-range-slider#76]
How to reverse thumbs positions? i need min on right, and max on left.

**Comment by githuboftigran** [comment]
@shareef-dweikat , use negated values. -max for minimum and -min for maximum. Then, in onValueChanged, negate the low and high values.

**Comment by mustafakameldev** [comment]
> @shareef-dweikat , use negated values. -max for minimum and -min for maximum. Then, in onValueChanged, negate the low and high values.

could you please get up more details
?
