### ISSUE TITLE
Cannot drag to Min value

### ISSUE THREAD

**Issue by abdymm** [githuboftigran/rn-range-slider#77]
Hi, i try with this
```
<Slider
        style={styles.slider}
        min={2}
        max={10}
        low={low}
        high={high}
        step={2}
        disableRange
        floatingLabel
        renderThumb={renderThumb}
        renderRail={renderRail}
        renderRailSelected={renderRailSelected}
        renderLabel={renderLabel}
        renderNotch={renderNotch}
        onValueChanged={handleValueChange}
      />
```
when i try to drag it back to lower value, which is, 2, i cant, it just stuck in 4 
is that any props that i miss for this case?

**Comment by githuboftigran** [comment]
@abdymm looks like you don't update low state variable when handleValueChange is triggered.

**Comment by abdymm** [comment]
ahh no, i see the other  [issue](https://github.com/githuboftigran/rn-range-slider/issues/71) , and after update with the latest, it running well now
Thanks! @githuboftigran
