### ISSUE TITLE
default values

### ISSUE THREAD

**Issue by Motazlubbad** [githuboftigran/rn-range-slider#79]
Hello,

I'm trying to  default values to the slider, for example my min 10 max 100 I want the selection to start from 40 not from 10. any help?

**Comment by githuboftigran** [comment]
`lowValue` prop is what you need, please read the documentation.

**Comment by gurbela** [comment]
There is no information about lowValue in the documentation,  also the component does not receive this value either

**Comment by gurbela** [comment]
The name of this prop is `low`

**Comment by anatooly** [comment]
this not defaultValue (like TextInput) that work without state. If we set **low** like this `low={3}` slider not work.
 ```
 const [low, setLow] = useState(3)
 
<RangeSlider
  low={low}
  onValueChanged={(low, high) => {
    setLow(low)
  }}
/>
```
