### ISSUE TITLE
Reset functionality

### ISSUE THREAD

**Issue by SaadAli-rolustech** [githuboftigran/rn-range-slider#80]
How can i reset the slider back to its initial state programmatically?

**Comment by githuboftigran** [comment]
@SaadAli-rolustech , use `low` and `high` props.

**Comment by SaadAli-rolustech** [comment]
can you share an example ?

**Comment by githuboftigran** [comment]
@SaadAli-rolustech , did you read the documentation?

**Comment by SaadAli-rolustech** [comment]
Yes, i am unable to do so

**Comment by githuboftigran** [comment]
@SaadAli-rolustech , low and high props DO work. Just set them to values you need and update them when a value is changed just like in Usage section of documentation.
