### ISSUE TITLE
Range slider UI isn't updated on resetting initialLowValue and initialHighValue

### ISSUE THREAD

**Issue by SaadAli-rolustech** [githuboftigran/rn-range-slider#82]
I am setting initialLowValue and initialHighValue value via state. If I reset the state to initial values, the slider re-renders but does not reflect the changes physically. The initialLowValue and initialHighValue values are reset but the slider UI doesn't change. How can I achieve this?

**Comment by githuboftigran** [comment]
@SaadAli-rolustech , there are no initialLowValue and initialHighValue props anymore. Please read the documentation.

**Comment by SaadAli-rolustech** [comment]
@githuboftigran I just went through the documentation. initialHighValue and initialLowValue have been replaced with high and low props respectively. I have assigned them values too but UI doesn't reflect any changes.

**Comment by githuboftigran** [comment]
@SaadAli-rolustech , they are not replaced, those props are **removed**. low and high values are not initial values. They are the actual values. If you set them to a constant, your slider will have pinned thumbs.
These props work just like prop `value` in TextInput.

**Comment by githuboftigran** [comment]
@SaadAli-rolustech https://reactnative.dev/docs/textinput#value

**Comment by SaadAli-rolustech** [comment]
@githuboftigran then which props are the initial values?

**Comment by githuboftigran** [comment]
There are no initial values. You should have state variables for low and high and then update them in onValueChange listener.

**Comment by mrshahzeb7** [comment]
underStood ! thanks
