### ISSUE TITLE
[iOS] textFormat %,d not working

### ISSUE THREAD

**Issue by AliRehman7141** [githuboftigran/rn-range-slider#84]
I need the commas separators like 123,456,789 for that the I used %,d it is working fine on android but not working on ios default format is %d which working without commas on both sides.

**text format %,d vs %d **

```
<RangeSlider
      ref={ref => this.rangeSliderRef = ref}
      style={{ width: '95%', alignSelf: 'center', height: 70, marginTop: -50, marginBottom: 10, }}
      gravity={'center'}
      min={50000}
      max={20000000}
      step={20}
      labelBackgroundColor={"#ffffff"}
      labelBorderColor={"#000000"}
      labelTextColor={"#000000"}
      selectionColor={"#00B7B0"}
      blankColor={"#828894"}
      onValueChanged={(low, high, fromUser) => {
          console.log('value', low, high)
          this.setState({ rangeLow: low, rangeHigh: high })
      }}
      textFormat={Platform.OS == 'android' ? "%,d" : "%d"}
  />
```

![simulator_screenshot_4554EA2F-AC80-458E-ADA6-0B948F614317](https://user-images.githubusercontent.com/33172988/108358834-02af8580-7211-11eb-953d-43da1f88217c.png) ![Screenshot_20210218-174353_FOHN](https://user-images.githubusercontent.com/33172988/108358967-325e8d80-7211-11eb-820a-d4160b8e4e59.jpg)

**Comment by githuboftigran** [comment]
@AliRehman7141 , the api was changed in version 2, please have a look.

**Comment by AliRehman7141** [comment]
@githuboftigran is %,d will works on both side?

**Comment by githuboftigran** [comment]
@AliRehman7141 , textFormat prop is removed in version 2, please read the documentation
