### ISSUE TITLE
Problem with RTL

### ISSUE THREAD

**Issue by rayansys** [githuboftigran/rn-range-slider#87]
Please fix RTL support

**Comment by rayansys** [comment]
```
export const useSelectedRail = (inPropsRef, containerWidthRef, thumbWidth, disableRange) => {
  const { current: left } = useRef(new Animated.Value(0));
  const { current: right } = useRef(new Animated.Value(0));
  const update = useCallback(() => {
    const { low, high, min, max } = inPropsRef.current;
    const { current: containerWidth } = containerWidthRef;
    const fullScale = (max - min) / (containerWidth - thumbWidth);
    const leftValue = (low - min) / fullScale;
    const rightValue = (max - high) / fullScale;
    left.setValue(disableRange ? 0 : leftValue);
    right.setValue(disableRange ? (containerWidth - thumbWidth) - leftValue : rightValue);
  }, [inPropsRef, containerWidthRef, disableRange, thumbWidth, left, right]);
  const styles = useMemo(() => ({
    position: 'absolute',
    left,
    right,
  }), [left, right]);
  return [styles, update];
};
```
You must use In18Manager inside this function

**Comment by githuboftigran** [comment]
@rayansys , what exactly do you mean by saying "fix RTL support?"
If you want lower thumb to be at right position and higher thumb to be at left position, that's not related to RTL.
Use this trick to achieve it:
https://github.com/githuboftigran/rn-range-slider/issues/76

**Comment by githuboftigran** [comment]
@rayansys , again, I don't get the problem. What works? What doesn't work? Could you please describe the problem with more details?
What is done, what is the result, what result was expected, screenshots, code, etc.

**Comment by rayansys** [comment]
My problem is that when the RTL mode is not active, it does not point and does not show correctly, in the submitted image.

**Comment by githuboftigran** [comment]
Will have a look in near future

**Comment by nammiharika** [comment]
Any update ???

**Comment by nammiharika** [comment]
In my case RTL is working like this. How can i resolve this?

https://user-images.githubusercontent.com/57613587/116537804-51aa2300-a904-11eb-90c5-96e1687122bc.mov

**Comment by wilkuintheair** [comment]
@nammiharika I was just fighting with this issue. Please try my PR (#98) and let me know if it works for you.
Any input is welcome

**Comment by githuboftigran** [comment]
@rayansys , fixed in version 2.1.0
https://www.npmjs.com/package/rn-range-slider/v/2.1.0

**Comment by nammiharika** [comment]
@githuboftigran In my case RTL is not working. Please see below attachment.
Slider is not working properly in RTL.

https://user-images.githubusercontent.com/57613587/129518935-ee663e61-c9e7-4681-9129-d4f4270f5203.mov

**Comment by githuboftigran** [comment]
@nammiharika , it works perfectly in the video attached :) What's the problem?

**Comment by nammiharika** [comment]
@githuboftigran, in RTL min price will be 0 and max price will be 100 right? But slider is working like LTR (0-100). In RTL it is working like (100-0). Please see below attachments. Both sliders are same. Both are working like (0-100).
LTR:-

https://user-images.githubusercontent.com/57613587/129519726-81b394c1-d248-4a8f-9001-189bef102861.mov

RTL:-


https://user-images.githubusercontent.com/57613587/129519808-405b25dd-47ce-4c19-85ba-8b5f1e509c00.mov

**Comment by githuboftigran** [comment]
@nammiharika , this is not an issue. Slider always works from left to right. If you need it to display 100 - 0, you need to treat low as high and high as low. Also you should probably use `100 - value` in renderLabel.

**Comment by nammiharika** [comment]
@githuboftigran, thank you for your reply. Could you please send me example for RTL. I can change low as high and high as low but it is not working for me.
Code:-
   <Slider
      style={styles.slider}
      min={max}
      max={min}
      step={1}
      disableRange={rangeDisabled}
      floatingLabel={floatingLabel}
      renderThumb={renderThumb}
      renderRail={renderRail}
      renderRailSelected={renderRailSelected}
      renderLabel={renderLabel}
      renderNotch={renderNotch}
      onValueChanged={handleValueChange}
    `/>`
    
    Screenshot:-
    

https://user-images.githubusercontent.com/57613587/129521239-56b785c0-3287-4ff7-9b0b-5413ac4d1dfb.mov

**Comment by githuboftigran** [comment]
@nammiharika , don't really know what is done there, but I won't add an example. Please figure out yourself. Just swap low and high values for your app. Show low value as high and high value as low in your texts.

**Comment by nammiharika** [comment]
Okay thank you for your reply @githuboftigran

**Comment by sudhakar9538** [comment]
@nammiharika the following code is working in RTL.

const [low, setLow] = useState(0);
  const [high, setHigh] = useState(500);
const renderLabel = useCallback(
    value => <Label text={I18nManager.isRTL ? 500 - value : value} />,
    [],
  );

https://user-images.githubusercontent.com/42173980/129559003-5c4453e4-8f5f-4143-af55-2db03044a64d.mov



const handleValueChange = useCallback((low1, high1) => {
    setLow(I18nManager.isRTL ? 500 - high1 : low1,);
    setHigh(I18nManager.isRTL ? 500 - low1 : high1);
  }, []);

<Slider
                    style={layoutStyles.slider}
                    min={0}
                    max={500}
                    step={1}
                    low={low}
                    high={high}
                    disableRange={false}
                    floatingLabel={floatingLabel}
                    renderThumb={renderThumb}
                    renderRail={renderRail}
                    renderRailSelected={renderRailSelected}
                    renderLabel={renderLabel}
                    renderNotch={renderNotch}
                    onValueChanged={handleValueChange}
                  />

**Comment by nammiharika** [comment]
@ sudhakar9538, thank you for reply. I tried your code it's working fine thank you for your response.
