### ISSUE TITLE
Non-number value in slider

### ISSUE THREAD

**Issue by ChenCodes** [githuboftigran/rn-range-slider#97]
Hi there,

I see in the API that `low` and `high` must be numbers. I'm wondering if it's possible for me to be able to set a `non-number` value as part of the slider range? For example I'm working with a list of ages from 18-80+, `80+` would be a string and not a number so that breaks the current API.

Any help /suggestions would be appreciated!

**Comment by ChenCodes** [comment]
Closing this issue - I saw the renderLabel solution.

**Comment by raajnadar-cb** [comment]
Can you add some examples of how you solved it with renderLabel?
