### ISSUE TITLE
OnReleased event would be very useful.

### ISSUE THREAD

**Issue by ibrag474** [githuboftigran/rn-range-slider#99]
Hi,

It would be great to be able to get only the final value when user releases the slider, `onReleased(value)` would be very useful.

**Comment by devWaleed** [comment]
+1 for this suggestion. We need onReleased(low, high) instead of onValueChanged(low, high). onValueChanged is very inefficient because updating state every time slider moves will crash app with Exception 'Maximum update depth reached'.

**Comment by githuboftigran** [comment]
@ibrag474 , @devWaleed , added props in v2.1.0
